-- =====================================================================
-- Email Report Infrastructure for Weekly Executive Summary
-- Run this AFTER dbt pipeline is deployed.
-- =====================================================================

-- 1. Create notification integration for email
CREATE NOTIFICATION INTEGRATION IF NOT EXISTS cost_email_integration
    TYPE = EMAIL
    ENABLED = TRUE
    ALLOWED_RECIPIENTS = ();  -- Add recipient emails here

-- 2. Create stored procedure to format and send the weekly report
CREATE OR REPLACE PROCEDURE COST_OPTIMIZATION_DB.PUBLICATION.send_weekly_report(recipients ARRAY)
RETURNS VARCHAR
LANGUAGE PYTHON
RUNTIME_VERSION = '3.8'
PACKAGES = ('snowflake-snowpark-python')
HANDLER = 'main'
AS
$$
def main(session, recipients):
    # Query the weekly executive report
    df = session.sql("""
        SELECT * FROM COST_OPTIMIZATION_DB.PUBLICATION.PUB__WEEKLY_EXECUTIVE_REPORT
    """).to_pandas()

    if df.empty:
        return 'No report data available'

    row = df.iloc[0]

    # Format HTML email
    wow_change = row.get('WOW_CHANGE_PCT', 0)
    wow_indicator = '📈' if wow_change > 0 else '📉' if wow_change < 0 else '➡️'

    html_body = f"""
    <html>
    <body style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h2 style="color: #2C3E50;">Snowflake Cost Weekly Report</h2>
        <p>Week starting: {row.get('WEEK_START', 'N/A')}</p>

        <h3>Cost Summary</h3>
        <table style="border-collapse: collapse; width: 100%;">
            <tr style="background-color: #f8f9fa;">
                <td style="padding: 8px; border: 1px solid #dee2e6;"><strong>This Week</strong></td>
                <td style="padding: 8px; border: 1px solid #dee2e6;">${row.get('THIS_WEEK_COST', 0):,.2f}</td>
            </tr>
            <tr>
                <td style="padding: 8px; border: 1px solid #dee2e6;"><strong>Last Week</strong></td>
                <td style="padding: 8px; border: 1px solid #dee2e6;">${row.get('LAST_WEEK_COST', 0):,.2f}</td>
            </tr>
            <tr style="background-color: #f8f9fa;">
                <td style="padding: 8px; border: 1px solid #dee2e6;"><strong>WoW Change</strong></td>
                <td style="padding: 8px; border: 1px solid #dee2e6;">{wow_indicator} {wow_change:+.1f}%</td>
            </tr>
        </table>

        <h3>Cost Breakdown</h3>
        <ul>
            <li>Compute: ${row.get('THIS_WEEK_COMPUTE', 0):,.2f}</li>
            <li>Storage: ${row.get('THIS_WEEK_STORAGE', 0):,.2f}</li>
            <li>Serverless: ${row.get('THIS_WEEK_SERVERLESS', 0):,.2f}</li>
        </ul>

        <h3>Alerts</h3>
        <p>{int(row.get('ACTIVE_ALERT_COUNT', 0))} new alert episodes this week</p>

        <h3>Savings Opportunities</h3>
        <p><strong>${row.get('TOTAL_UNREALISED_SAVINGS', 0):,.2f}/month</strong> in unrealised savings</p>

        <hr style="border: 1px solid #eee;">
        <p style="color: #999; font-size: 12px;">
            Generated by the Snowflake Cost Optimisation Framework.
            Log in to the dashboard for full details.
        </p>
    </body>
    </html>
    """

    # Send email to each recipient
    for recipient in recipients:
        session.sql(f"""
            CALL SYSTEM$SEND_EMAIL(
                'cost_email_integration',
                '{recipient}',
                'Snowflake Cost Weekly Report - Week of {row.get("WEEK_START", "N/A")}',
                '{html_body.replace("'", "''")}',
                'text/html'
            )
        """).collect()

    return f'Report sent to {len(recipients)} recipients'
$$;

-- 3. Create scheduled task (starts suspended — manual resume required)
CREATE TASK IF NOT EXISTS COST_OPTIMIZATION_DB.PUBLICATION.send_weekly_report_task
    WAREHOUSE = 'COST_OPT_WH'
    SCHEDULE = 'USING CRON 0 8 * * 1 UTC'  -- Monday 8 AM UTC
    COMMENT = 'Sends weekly cost executive summary email'
AS
    CALL COST_OPTIMIZATION_DB.PUBLICATION.send_weekly_report(
        ARRAY_CONSTRUCT()  -- Add recipient emails here
    );

-- Task is created suspended. To enable:
-- ALTER TASK COST_OPTIMIZATION_DB.PUBLICATION.send_weekly_report_task RESUME;
