name: 'cost_optimization'
version: '1.0.0'

profile: 'cost_optimization'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

on-run-end:
  - "{{ call_send_teams_alerts() }}"

seeds:
  cost_optimization:
    +schema: SEEDS
    alert_suppressions:
      +column_types:
        alert_id: varchar
        resource_value: varchar
        suppression_reason: varchar
        created_by: varchar
        start_date: date
        end_date: date
    bank_holidays:
      +column_types:
        holiday_date: date

models:
  cost_optimization:
    staging:
      +materialized: view
      +schema: STAGING
    intermediate:
      +materialized: table
      +schema: INTERMEDIATE
    publication:
      +materialized: table
      +schema: PUBLICATION
    alerts:
      +materialized: table
      +schema: INTERMEDIATE
