name: 'cost_optimization'
version: '1.0.0'

profile: 'cost_optimization'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

on-run-end:
  - "{% if execute and flags.WHICH in ('run', 'build') %}BEGIN CALL send_teams_alerts(); EXCEPTION WHEN OTHER THEN RETURN 'send_teams_alerts not deployed yet'; END;{% endif %}"

seeds:
  cost_optimization:
    +schema: SEEDS

models:
  cost_optimization:
    staging:
      +materialized: view
      +schema: STAGING
    intermediate:
      +materialized: table
      +schema: INTERMEDIATE
    publication:
      +materialized: table
      +schema: PUBLICATION
    alerts:
      +materialized: table
      +schema: INTERMEDIATE
