"""SQL query constants for the Cost Optimization Dashboard."""

# Schema references
PUB = "COST_OPTIMIZATION_DB.PUBLICATION"
INT = "COST_OPTIMIZATION_DB.INTERMEDIATE"

# ── Executive Summary ─────────────────────────────────────────────────
COST_SUMMARY = f"SELECT * FROM {PUB}.PUB__COST_SUMMARY ORDER BY MONTH DESC"

COST_TRENDS_DAILY = f"""
SELECT * FROM {PUB}.PUB__COST_TRENDS_DAILY
WHERE DATE >= DATEADD('day', -{{days}}, CURRENT_DATE())
ORDER BY DATE
"""

TOP_WAREHOUSES = f"""
SELECT WAREHOUSE_NAME, TOTAL_COST_USD
FROM {PUB}.PUB__COST_BY_WAREHOUSE
ORDER BY TOTAL_COST_USD DESC
LIMIT 5
"""

TOP_USERS = f"""
SELECT USER_NAME, TOTAL_COST_USD
FROM {PUB}.PUB__COST_BY_USER
ORDER BY TOTAL_COST_USD DESC
LIMIT 5
"""

# ── Warehouse Deep Dive ──────────────────────────────────────────────
WAREHOUSE_LIST = f"""
SELECT DISTINCT WAREHOUSE_NAME FROM {PUB}.PUB__COST_BY_WAREHOUSE
ORDER BY WAREHOUSE_NAME
"""

WAREHOUSE_DETAILS = f"SELECT * FROM {PUB}.PUB__COST_BY_WAREHOUSE"

WAREHOUSE_EFFICIENCY = f"SELECT * FROM {PUB}.PUB__WAREHOUSE_EFFICIENCY"

WAREHOUSE_DAILY_CREDITS = f"""
SELECT * FROM {INT}.INT__WAREHOUSE_DAILY_CREDITS
WHERE DATE >= DATEADD('day', -{{days}}, CURRENT_DATE())
ORDER BY DATE
"""

IDLE_PERIODS = f"""
SELECT * FROM {INT}.INT__IDLE_WAREHOUSE_PERIODS
WHERE WAREHOUSE_NAME = '{{warehouse}}'
ORDER BY IDLE_START DESC
LIMIT 50
"""

# ── Team Attribution ──────────────────────────────────────────────────
TEAM_COST_DASHBOARD = f"SELECT * FROM {PUB}.PUB__TEAM_COST_DASHBOARD ORDER BY MONTH DESC"

COST_BY_USER = f"SELECT * FROM {PUB}.PUB__COST_BY_USER ORDER BY TOTAL_COST_USD DESC"

COST_BY_QUERY_TYPE = f"SELECT * FROM {PUB}.PUB__COST_BY_QUERY_TYPE ORDER BY TOTAL_COST_USD DESC"

# ── Storage Explorer ──────────────────────────────────────────────────
STORAGE_ANALYSIS = f"SELECT * FROM {PUB}.PUB__STORAGE_ANALYSIS ORDER BY TOTAL_TB DESC"

STORAGE_BY_DATABASE = f"""
SELECT
    DATABASE_NAME,
    SUM(ACTIVE_TB) AS ACTIVE_TB,
    SUM(TIME_TRAVEL_TB) AS TIME_TRAVEL_TB,
    SUM(FAILSAFE_TB) AS FAILSAFE_TB,
    SUM(TOTAL_TB) AS TOTAL_TB,
    SUM(ESTIMATED_MONTHLY_COST_USD) AS TOTAL_COST_USD
FROM {PUB}.PUB__STORAGE_ANALYSIS
GROUP BY DATABASE_NAME
ORDER BY TOTAL_TB DESC
"""

# ── Trend Analysis ───────────────────────────────────────────────────
ANOMALY_DAYS = f"""
SELECT * FROM {PUB}.PUB__COST_TRENDS_DAILY
WHERE IS_ANOMALY = TRUE
ORDER BY DATE DESC
"""

# ── Data Freshness ──────────────────────────────────────────────────
DATA_FRESHNESS = f"""
SELECT SOURCE_NAME, MODEL_NAME, LATEST_RECORD_AT, STALENESS_MINUTES, FRESHNESS_STATUS
FROM {PUB}.PUB__DATA_FRESHNESS
ORDER BY STALENESS_MINUTES DESC
"""

DATA_FRESHNESS_SUMMARY = f"""
SELECT OVERALL_FRESHNESS_STATUS, OVERALL_MAX_STALENESS_MINUTES, OVERALL_OLDEST_RECORD_AT
FROM {PUB}.PUB__DATA_FRESHNESS
LIMIT 1
"""

# ── Cost Forecast ───────────────────────────────────────────────────
COST_FORECAST = f"SELECT * FROM {PUB}.PUB__COST_FORECAST ORDER BY MONTH"

TEAM_FORECAST = f"""
SELECT TEAM_NAME, FORECAST_MONTH, PREDICTED_MONTHLY_COST,
       CI_LOWER, CI_UPPER, MONTHLY_TREND, DATA_MONTHS
FROM {INT}.INT__TEAM_COST_FORECAST
ORDER BY TEAM_NAME, FORECAST_MONTH
"""

PROJECTED_ANNUAL_SPEND = f"""
SELECT DISTINCT PROJECTED_ANNUAL_SPEND
FROM {PUB}.PUB__COST_FORECAST
LIMIT 1
"""

# ── Recommendation ROI ──────────────────────────────────────────────
RECOMMENDATION_ROI = f"SELECT * FROM {PUB}.PUB__RECOMMENDATION_ROI"

# ── Weekly Report ───────────────────────────────────────────────────
WEEKLY_REPORT = f"SELECT * FROM {PUB}.PUB__WEEKLY_EXECUTIVE_REPORT"
